"use strict";
let hello = "Hello ts";
hello = "ts";
console.log(hello);
let ts = "Hello typeScript";
ts = "type";
console.log(ts);
let message = "hello typeScript";
console.log(message);
let charge = 323;
console.log(charge);
